# Generated by Django 2.2.6 on 2019-10-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('apellido', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('dni', models.CharField(max_length=80)),
                ('foto', models.ImageField(default='federacion/jugadores/default.png', upload_to='federacion/jugadores/')),
            ],
        ),
    ]
