# Generated by Django 2.2.6 on 2019-10-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20191012_1519'),
        ('jugadores', '0002_auto_20191012_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
        ),
    ]
