# Generated by Django 2.2.6 on 2019-10-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_auto_20191015_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='logo',
            field=models.ImageField(default='federacion/liga/default.png', upload_to='federacion/liga/'),
        ),
    ]
