# Generated by Django 2.2.6 on 2019-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(default='federacion/clubes/default.png', upload_to='federacion/clubes/')),
            ],
        ),
    ]
