# Generated by Django 2.2.6 on 2019-10-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
        ('club', '0002_auto_20191012_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liga.Division'),
        ),
    ]
