# Generated by Django 2.2.6 on 2019-10-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_auto_20191015_0052'),
        ('club', '0003_club_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=0)),
                ('temporada', models.PositiveIntegerField(default=0)),
                ('equipo1', models.PositiveIntegerField(default=0)),
                ('equipo2', models.PositiveIntegerField(default=0)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liga.Division')),
            ],
        ),
    ]
