# Generated by Django 2.2.6 on 2019-10-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_fechas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.PositiveIntegerField(default=0)),
                ('visitante', models.PositiveIntegerField(default=0)),
                ('fecha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Fechas')),
            ],
        ),
    ]
