# Generated by Django 2.2.6 on 2019-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_auto_20191015_0052'),
        ('club', '0005_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liga.Division'),
        ),
    ]
