# Generated by Django 2.2.6 on 2019-10-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_resultados_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechas',
            name='goleslocal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fechas',
            name='golesvisita',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fechas',
            name='jugado',
            field=models.BooleanField(default=False),
        ),
    ]
