# Generated by Django 2.2.6 on 2019-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20191027_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechas',
            name='goleslocal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fechas',
            name='golesvisita',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
